services:
  prodev_db:
    image: mysql:8.0
    container_name: prodev_db
    environment:
      MYSQL_ROOT_PASSWORD: ict555!!!
      MYSQL_DATABASE: prodev_db
    ports:
      - "3307:3306"
    volumes:
      - prodev_db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./prodev
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # ใช้ host.docker.internal เพื่อให้ backend container connect MySQL ของ host machine
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/prodev_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ict555!!!
      JWT_EXPIRATION: 86400000
      UPLOAD_DIR: uploads/products
    volumes:
      # รูปเก่า
      - ./prodev/uploads/products:/uploads/products
      # รูปใหม่
      - ./prodev/uploads/products:/app/uploads/products
    depends_on:
      - prodev_db

  frontend:
    build:
      context: ./prodev-frontend/front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  prodev_db_data:
