name: CI/CD - Build, Test & Push Docker

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 🔹 Build Backend & Frontend Images
      - name: Build Docker Images
        run: |
          echo "🔨 Building backend and frontend Docker images..."
          docker build -t armmer/prodev-backend ./prodev
          docker build -t armmer/prodev-frontend ./prodev-frontend/front-end

      # 🔹 Start Containers with docker-compose
      - name: Start Containers
        run: |
          echo "🚀 Starting containers with docker-compose..."
          docker-compose -f ./docker-compose.yml up -d
          docker ps

      # 🔹 Run E2E Tests
      - name: Run E2E Tests
        working-directory: ./e2e
        run: |
          echo "🧪 Installing dependencies..."
          npm ci
          echo "🧪 Running Cypress end-to-end tests..."
          npx cypress run --headless --browser electron --config baseUrl=http://localhost:3000

      # 🔹 Push Docker Images to Docker Hub
      - name: Push Docker Images
        run: |
          echo "📦 Pushing Docker images to Docker Hub..."
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push armmer/prodev-backend
          docker push armmer/prodev-frontend
          docker logout

    # 🔹 Cleanup after job
    post:
      always:
        - name: Cleanup containers
          run: |
            echo "🧹 Cleaning up containers..."
            docker-compose -f ./docker-compose.yml down || exit 0
        - name: Cleanup workspace
          run: |
            echo "🧹 Cleaning up workspace..."
            rm -rf *
