# CI/CD - Build, Push & E2E Test
name: CI/CD - Build, Push & E2E Test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./prodev
          file: ./prodev/Dockerfile
          push: true
          tags: |
            armmer/prodev-backend:latest
            armmer/prodev-backend:${{ github.sha }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./prodev-frontend/front-end
          file: ./prodev-frontend/front-end/Dockerfile
          push: true
          tags: |
            armmer/prodev-frontend:latest
            armmer/prodev-frontend:${{ github.sha }}

      - name: Start all containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for backend & frontend
        run: |
          for i in {1..30}; do
            # ตรวจสอบจาก network ภายใน container
            if docker compose exec frontend sh -c "curl -s http://localhost:3000 >/dev/null" \
               && docker compose exec backend sh -c "curl -s http://localhost:8080 >/dev/null"; then
              echo "All containers ready!"
              break
            fi
            echo "Waiting..."
            sleep 2
          done

      - name: Run Cypress E2E Tests
        run: |
          docker run --rm \
            --network prodev_default \
            -v ${{ github.workspace }}/e2e:/e2e \
            -w /e2e \
            -e CYPRESS_BASE_URL=http://frontend:3000 \
            cypress/included:15.2.0

      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.yml down
