name: CI/CD - Build, Push & E2E Test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4) Build & Push Backend
      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./prodev
          file: ./prodev/Dockerfile
          push: true
          tags: |
            armmer/prodev-backend:latest
            armmer/prodev-backend:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/ProDev02/prodev

      # 5) Build & Push Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./prodev-frontend/front-end
          file: ./prodev-frontend/front-end/Dockerfile
          push: true
          tags: |
            armmer/prodev-frontend:latest
            armmer/prodev-frontend:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/ProDev02/prodev

      # 6) Run mocked E2E tests (no Docker)
      - name: Install & Run Cypress (mocked)
        working-directory: ./e2e
        run: |
          npm ci
          npx cypress run --headless --browser chrome
        env:
          BACKEND_URL: ""  # ใช้ mocked API ใน spec

