name: CI/CD - Build, Push & E2E Test

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build & Push Backend (optional, แต่ push ไว้ก่อน)
      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./prodev
          file: ./prodev/Dockerfile
          push: true
          tags: |
            armmer/prodev-backend:latest
            armmer/prodev-backend:${{ github.sha }}

      # 5. Build & Push Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./prodev-frontend/front-end
          file: ./prodev-frontend/front-end/Dockerfile
          push: true
          tags: |
            armmer/prodev-frontend:latest
            armmer/prodev-frontend:${{ github.sha }}

      # 6. Start frontend container
      - name: Start frontend container
        run: |
          docker compose -f docker-compose.yml up -d frontend
          echo "Waiting for frontend to be ready..."
          for i in {1..20}; do
            if curl -s http://localhost:3000; then
              echo "Frontend ready!"
              break
            fi
            sleep 2
          done

      # 7. Run Cypress E2E Tests
      - name: Run Cypress E2E Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/e2e:/e2e \
            -w /e2e \
            -e CYPRESS_BASE_URL=http://host.docker.internal:3000 \
            cypress/included:15.2.0

      # 8. Stop containers (always)
      - name: Stop containers
        if: always()
        run: docker compose -f docker-compose.yml down
