name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: self-hosted  # ใช้ self-hosted runner บน Windows

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push
      - name: Build & Push Backend
        run: |
          docker build -t armmer/prodev-backend:latest ./prodev
          docker push armmer/prodev-backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t armmer/prodev-frontend:latest ./prodev-frontend/front-end
          docker push armmer/prodev-frontend:latest

      # Run Docker Compose
      - name: Start Docker containers
        run: |
          docker-compose -f ./docker-compose.yml up -d --build
          docker ps

      # Run E2E Tests
      - name: Install Cypress dependencies
        run: |
          cd e2e
          npm ci
          npx cypress run --headless --browser electron --config baseUrl=http://localhost:3000

      # Login docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  cleanup:
    name: Cleanup Containers
    runs-on: self-hosted

    steps:
      - name: Clean up Docker containers
        run: |
          docker-compose -f ./docker-compose.yml down
