name: CI/CD - Build Docker & Deploy K8s

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push Backend
      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./prodev
          file: ./prodev/Dockerfile
          push: true
          tags: armmer/prodev-backend:latest

      # Build & Push Frontend
      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./prodev-frontend/front-end
          file: ./prodev-frontend/front-end/Dockerfile
          push: true
          tags: armmer/prodev-frontend:latest

      # Setup kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Deploy to K8s
      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl apply -f k8s-deployment.yml
