name: CI/CD - Build Docker & Deploy K8s

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted  # ✅ เปลี่ยนเป็น self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Docker & Kubernetes
        run: |
          docker version
          kubectl version
          kubectl get nodes

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          docker build -t armmer/prodev-backend:latest ./prodev
          docker push armmer/prodev-backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t armmer/prodev-frontend:latest ./prodev-frontend/front-end
          docker push armmer/prodev-frontend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-deployment.yml
